id: AE1ADD143
base_file: fDEB6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:44:30.447033
  last_modified_at: 2022-05-30 21:44:30.447036
