id: AE1ADD143
base_file: f4BB0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:44:30.443643
  last_modified_at: 2022-05-30 21:44:30.443646
