id: AE1ADD143
base_file: f334E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:44:30.441587
  last_modified_at: 2022-05-30 21:44:30.441596
